/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCard: typeof import('./../components/AuthCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    RippleBackground: typeof import('./../components/RippleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WaveBackground: typeof import('./../components/WaveBackground.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
